export default {
  providers: {
    name: 'faker.name.findName()',
    maleName: "faker.name.findName('','',0)",
    femaleName: "faker.name.findName('','',1)",
    femaleFirstName: 'faker.name.firstName(1)',
    femaleLastName: 'faker.name.lastName(1)',
    maleFirstName: 'faker.name.firstName(0)',
    maleLastName: 'faker.name.lastName(0)',
    domain: 'faker.internet.domainName()',
    age: 'faker.datatype.number(100)',
    jobTitle: 'faker.name.jobTitle()',
    jobDescriptor: 'faker.name.jobDescriptor()',
    jobArea: 'faker.name.jobArea()',
    jobType: 'faker.name.jobType()',
    //company
    companyName: 'faker.company.companyName()',
    companySuffix: 'faker.company.companySuffix()',
    catchPhrase: 'faker.company.catchPhrase()',
    catchPhraseDescriptor: 'faker.company.catchPhraseDescriptor()',
    catchPhraseAdjective: 'faker.company.catchPhraseAdjective()',
    catchPhraseNoun: 'faker.company.catchPhraseNoun()',
    bs: 'faker.company.bs()',
    bsAdjective: 'faker.company.bsAdjective()',
    bsNoun: 'faker.company.bsNoun()',
    bsBuzz: 'faker.company.bsBuzz()',
    suffixes: 'faker.company.suffixes()',
    //address
    zipCode: 'faker.address.zipCode()',
    cityPrefix: 'faker.address.cityPrefix()',
    citySuffix: 'faker.address.citySuffix()',
    city: 'faker.address.city()',
    cityName: 'faker.address.cityName()',
    streetName: 'faker.address.streetName()',
    streetSuffix: 'faker.address.streetSuffix()',
    streetPrefix: 'faker.address.streetPrefix()',
    secondaryAddress: 'faker.address.secondaryAddress()',
    county: 'faker.address.county()',
    country: 'faker.address.country()',
    state: 'faker.address.state()',
    stateAbbr: 'faker.address.stateAbbr()',
    latitude: 'faker.address.latitude()',
    longitude: 'faker.address.longitude()',
    direction: 'faker.address.direction()',
    cardinalDirection: 'faker.address.cardinalDirection()',
    ordinalDirection: 'faker.address.ordinalDirection()',
    nearbyGPSCoordinate: 'faker.address.nearbyGPSCoordinate()',
    timeZone: 'faker.address.timeZone()',
  },
  processors: [
    'joiner',
    'joinerSpace',
    'joinerDot',
    'joinerComma',
    'joinerHash',
    'append',
    'prepend',
    'randomNumber',
    'emailDomain'
  ],
  providersWithParams: {
    zipCodeByState: 'faker.address.zipCodeByState',
    streetAddress: 'faker.address.streetAddress',
    countryCode: 'faker.address.countryCode', //param default=alpha-2, accepts alpha-3
  }
}
