export default {
  providers: {
    name: 'faker.name.findName()',
    maleName: "faker.name.findName('','',0)",
    femaleName: "faker.name.findName('','',1)",
    femaleFirstName: 'faker.name.firstName(1)',
    femaleLastName: 'faker.name.lastName(1)',
    maleFirstName: 'faker.name.firstName(0)',
    maleLastName: 'faker.name.lastName(0)',
    femaleMiddleName: 'faker.name.middleName(1)',
    maleMiddleName: 'faker.name.middleName(0)',
    gender: 'faker.name.gender(0)',
    namePrefix: 'faker.name.prefix(0)',
    nameSuffix: 'faker.name.suffix(0)',
    nameTitle: 'faker.name.title(0)',
    domain: 'faker.internet.domainName()',
    age: 'faker.datatype.number(100)',
    jobTitle: 'faker.name.jobTitle()',
    jobDescriptor: 'faker.name.jobDescriptor()',
    jobArea: 'faker.name.jobArea()',
    jobType: 'faker.name.jobType()',
    //company
    companyName: 'faker.company.companyName()',
    companySuffix: 'faker.company.companySuffix()',
    catchPhrase: 'faker.company.catchPhrase()',
    catchPhraseDescriptor: 'faker.company.catchPhraseDescriptor()',
    catchPhraseAdjective: 'faker.company.catchPhraseAdjective()',
    catchPhraseNoun: 'faker.company.catchPhraseNoun()',
    bs: 'faker.company.bs()',
    bsAdjective: 'faker.company.bsAdjective()',
    bsNoun: 'faker.company.bsNoun()',
    bsBuzz: 'faker.company.bsBuzz()',
    suffixes: 'faker.company.suffixes()',
    //address
    zipCode: 'faker.address.zipCode()',
    cityPrefix: 'faker.address.cityPrefix()',
    citySuffix: 'faker.address.citySuffix()',
    city: 'faker.address.city()',
    cityName: 'faker.address.cityName()',
    streetName: 'faker.address.streetName()',
    streetSuffix: 'faker.address.streetSuffix()',
    streetPrefix: 'faker.address.streetPrefix()',
    secondaryAddress: 'faker.address.secondaryAddress()',
    county: 'faker.address.county()',
    country: 'faker.address.country()',
    state: 'faker.address.state()',
    stateAbbr: 'faker.address.stateAbbr()',
    latitude: 'faker.address.latitude()',
    longitude: 'faker.address.longitude()',
    direction: 'faker.address.direction()',
    cardinalDirection: 'faker.address.cardinalDirection()',
    ordinalDirection: 'faker.address.ordinalDirection()',
    nearbyGPSCoordinate: 'faker.address.nearbyGPSCoordinate()',
    timeZone: 'faker.address.timeZone()',
    //animal
    dog:'faker.animal.dog()',
    cat:'faker.animal.cat()',
    snake:'faker.animal.snake()',
    bear:'faker.animal.bear()',
    lion:'faker.animal.lion()',
    cetacean:'faker.animal.cetacean()',
    horse:'faker.animal.horse()',
    bird:'faker.animal.bird()',
    cow:'faker.animal.cow()',
    fish:'faker.animal.fish()',
    crocodilia:'faker.animal.crocodilia()',
    insect:'faker.animal.insect()',
    rabbit:'faker.animal.rabbit()',
    type:'faker.animal.type()',
    //commerce
    color:'faker.commerce.color()',
    department:'faker.commerce.department()',
    productName:'faker.commerce.productName()',
    productAdjective:'faker.commerce.productAdjective()',
    productMaterial:'faker.commerce.productMaterial()',
    product:'faker.commerce.product()',
    productDescription:'faker.commerce.productDescription()',
    //database
    column:'faker.database.column()',
    type:'faker.database.type()',
    collation:'faker.database.collation()',
    engine:'faker.database.engine()',
    //data types
    number:'faker.datatype.number()',
    float:'faker.datatype.float()',
    datetime:'faker.datatype.datetime()',
    string:'faker.datatype.string()',
    uuid:'faker.datatype.uuid()',
    hexaDecimal:'faker.datatype.hexaDecimal()',
    boolean:'faker.datatype.boolean()',
    json:'faker.datatype.json()',
    array:'faker.datatype.array()',
    //finance
    account:'faker.finance.account()',
    accountName:'faker.finance.accountName()',
    routingNumber:'faker.finance.routingNumber()',
    mask:'faker.finance.mask()',
    amount:'faker.finance.amount()',
    transactionType:'faker.finance.transactionType()',
    currencyCode:'faker.finance.currencyCode()',
    currencyName:'faker.finance.currencyName()',
    currencySymbol:'faker.finance.currencySymbol()',
    bitcoinAddress:'faker.finance.bitcoinAddress()',
    litecoinAddress:'faker.finance.litecoinAddress()',
    creditCardNumber:'faker.finance.creditCardNumber()',
    creditCardCVV:'faker.finance.creditCardCVV()',
    ethereumAddress:'faker.finance.ethereumAddress()',
    iban:'faker.finance.iban()',
    bic:'faker.finance.bic()',
    transactionDescription:'faker.finance.transactionDescription()',
    //git
    branch:'faker.git.branch()',
    commitEntry:'faker.git.commitEntry()',
    commitMessage:'faker.git.commitMessage()',
    commitSha:'faker.git.commitSha()',
    shortSha:'faker.git.shortSha()',
    //hacker
    abbreviation:'faker.hacker.abbreviation()',
    adjective:'faker.hacker.adjective()',
    noun:'faker.hacker.noun()',
    verb:'faker.hacker.verb()',
    ingverb:'faker.hacker.ingverb()',
    phrase:'faker.hacker.phrase()',
    //image
    image:'faker.image.image()',
    imageavatar:'faker.image.avatar()',
    imageUrl:'faker.image.imageUrl()',
    abstract:'faker.image.abstract()',
    animals:'faker.image.animals()',
    business:'faker.image.business()',
    cats:'faker.image.cats()',
    city:'faker.image.city()',
    food:'faker.image.food()',
    nightlife:'faker.image.nightlife()',
    fashion:'faker.image.fashion()',
    people:'faker.image.people()',
    nature:'faker.image.nature()',
    sports:'faker.image.sports()',
    technics:'faker.image.technics()',
    transport:'faker.image.transport()',
    dataUri:'faker.image.dataUri()',
    lorempixel:'faker.image.lorempixel()',
    unsplash:'faker.image.unsplash()',
    lorempicsum:'faker.image.lorempicsum()',
    //internet
    avatar:'faker.internet.avatar()',
    email:'faker.internet.email()',
    exampleEmail:'faker.internet.exampleEmail()',
    userName:'faker.internet.userName()',
    protocol:'faker.internet.protocol()',
    httpMethod:'faker.internet.httpMethod()',
    url:'faker.internet.url()',
    domainName:'faker.internet.domainName()',
    domainSuffix:'faker.internet.domainSuffix()',
    domainWord:'faker.internet.domainWord ()',
    ip:'faker.internet.ip()',
    ipv6:'faker.internet.ipv6()',
    port:'faker.internet.port()',
    userAgent:'faker.internet.userAgent()',
    color:'faker.internet.color()',
    mac:'faker.internet.mac()',
    password:'faker.internet.password()',
    //music
    genre:'faker.music.genre()',
    //phome
    phoneNumber:'faker.phone.phoneNumber()',
    phoneFormats:'faker.phone.phoneFormats()',
    //system
    fileName:'faker.system.fileName()',
    commonFileName:'faker.system.commonFileName()',
    mimeType:'faker.system.mimeType()',
    commonFileType:'faker.system.commonFileType()',
    commonFileExt:'faker.system.commonFileExt()',
    fileType:'faker.system.fileType()',
    fileExt:'faker.system.fileExt()',
    directoryPath:'faker.system.directoryPath()',
    filePath:'faker.system.filePath()',
    semver:'faker.system.semver()',
    //time
    recent:'faker.time.recent()',
    //vehicle
    vehicle:'faker.vehicle.vehicle()',
    manufacturer:'faker.vehicle.manufacturer()',
    manufacturer:'faker.vehicle.manufacturer()',
    model:'faker.vehicle.model()',
    type:'faker.vehicle.type()',
    fuel:'faker.vehicle.fuel()',
    vin:'faker.vehicle.vin()',
    color:'faker.vehicle.color()',
    vrm:'faker.vehicle.vrm()',
    bicycle:'faker.vehicle.bicycle()',

  },
  processors: [
    'joiner',
    'joinerSpace',
    'joinerDot',
    'joinerComma',
    'joinerHash',
    'append',
    'prepend',
    'randomNumber',
    'emailDomain',
    'year'
  ],
  providersWithParams: {
    zipCodeByState: 'faker.address.zipCodeByState',
    streetAddress: 'faker.address.streetAddress',
    countryCode: 'faker.address.countryCode', //param default=alpha-2, accepts alpha-3
    price:'faker.commerce.price', //min, max, dec, symbol
    past:'faker.date.past',//years,dateRef
    future:'faker.date.future',//years,dateRef
    between:'faker.date.between', //from,to
    betweens:'faker.date.betweens', //from,to
    recent:'faker.date.recent', //days.dateRef
    soon:'faker.date.soon', //days.dateRef
    month:'faker.date.month', //days.dateRef
    weekday:'faker.date.weekday', //days.dateRef
    //lorem
    word:'faker.lorem.word',
    words:'faker.lorem.words',
    sentence:'faker.lorem.sentence',
    sentences:'faker.lorem.sentences',
    slug:'faker.lorem.slug',
    paragraph:'faker.lorem.paragraph',
    paragraphs:'faker.lorem.paragraphs',
    text:'faker.lorem.text',
    lines:'faker.lorem.lines',
    //phone
    phoneNumberFormat:'faker.phone.phoneNumberFormat',
  }
}
